### ISSUE TITLE
Falsche/fehlerhafte Links

### ISSUE THREAD

**Issue by markemotion** [markemotion/web2.0#2]
- http://dev.markemotion.de/marke/ Kachel "Marketing Strategie"
- http://dev.markemotion.de/marke/ in der Copy

**Comment by Julia-markemotion** [comment]
Bei den Links ist mir noch aufgefallen, dass die, die zu den "News" jeweils leiten, ...portfolio-item... heißen. Finde ich persönlich nicht so schön. Vielleicht kann man die schöner gestalten, wenn möglich.

**Comment by Julia-markemotion** [comment]
Done!
